development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= Rails.application.credentials.redis[:url] %>
  port: <%= Rails.application.credentials.redis[:port] %>
  password: <%= Rails.application.credentials.redis[:password] %>
  channel_prefix: aid_platform_api_production
