development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>
  port: <%= ENV['REDIS_PORT'] %>
  password: <%= ENV['REDIS_PASSWORD'] %>
  channel_prefix: aid_platform_api_production
